Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: allowSqs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - sqs:*
              Resource: arn:aws:sqs:*:*:*
        - PolicyName: allowDynamoDb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - dynamodb:*
              Resource: arn:aws:dynamodb:*:*:*

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: ec2-instance-profile
      Path: "/"
      Roles: [!Ref EC2Role]

  ApiInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP/SSH
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  BooksApiInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07df274a488ca9195
      IamInstanceProfile: !Ref EC2InstanceProfile
      InstanceType: t2.micro
      KeyName: aws-key2
      SecurityGroups:
        - !Ref ApiInstanceSecurityGroup
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
        sudo yum install docker -y
        sudo service docker start