Resources:
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: arn:aws:sqs:eu-central-1:554236477482:sqs-queue-luigfsddasf
      FunctionName: sqsChangeLambda