name: Lambda Instance Change

on:
  workflow_dispatch:
  push:
    paths:
      - 'templates/lambda-instance.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Lambda Instance Change
        run: |
          aws cloudformation update-stack --stack-name dev-stage-lambda-instance --template-body file://templates/lambda-instance.yml --region eu-central-1
