name: Start New Stage

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Update Lambda
        run: |
          aws cloudformation create-stack --stack-name dev-stage-lambda-infrastructure --template-body file://templates/lambda-infrastructure.yml --region eu-central-1 --capabilities CAPABILITY_NAMED_IAM
          #aws cloudformation create-stack --stack-name dev-stage-lambda --template-body file://templates/lambda.yml --region eu-central-1
          aws cloudformation create-stack --stack-name dev-stage-db-instance --template-body file://templates/db-instance.yml --region eu-central-1
          aws cloudformation create-stack --stack-name dev-stage-api-instance --template-body file://templates/api-instance.yml --region eu-central-1
          aws cloudformation create-stack --stack-name dev-stage-queue --template-body file://templates/queue.yml --region eu-central-1
          aws cloudformation create-stack --stack-name dev-stage-log-bucket --template-body file://templates/log-bucket.yml --region eu-central-1
