name: Start Stage

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Running Lambda Deployment
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: VahePetrosian
          repo: BooksManagmentLambda
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: main.yml

      - name: Run Lambda Repository Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh api repos/:VahePetrosian/BooksManagmentLambda/dispatches --raw-field event_type=template-start-trigger

      - name: Create Lambda Infrastructure
        run: |
          aws cloudformation create-stack --stack-name dev-stage-lambda-instance --template-body file://templates/lambda-instance.yml
          aws cloudformation wait stack-create-complete --stack-name dev-stage-lambda-instance

